from collections import deque

from rules.detections import (
    rule_brute_force,
    rule_port_scan,
    rule_large_outbound_transfer,
    rule_dns_burst,
    rule_unusual_destination_port,
    rule_long_connection,
    rule_connection_flood,
    rule_periodic_beacon,
)


# ============================================================
# REGISTERED DETECTION RULES
# ============================================================

RULES = [
    rule_brute_force,
    rule_port_scan,
    rule_large_outbound_transfer,
    rule_dns_burst,
    rule_unusual_destination_port,
    rule_long_connection,
    rule_connection_flood,
    rule_periodic_beacon,
]

_SEEN_UID_LIMIT = 100000
_seen_uids = set()
_seen_uid_order = deque()


def evaluate_event(event):
    """
    Evaluate one Zeek event against every registered detection.

    Returns:
        list[dict]: alerts generated by the event.
    """

    uid = event.get("uid")
    if uid:
        uid = str(uid)
        if uid in _seen_uids:
            return []
        _seen_uids.add(uid)
        _seen_uid_order.append(uid)
        if len(_seen_uid_order) > _SEEN_UID_LIMIT:
            _seen_uids.discard(_seen_uid_order.popleft())

    alerts = []

    for rule in RULES:

        try:
            result = rule(event)

            if not result:
                continue

            alert = {
                **result,

                # ------------------------------------------------
                # Common Zeek event context
                # ------------------------------------------------

                "src_ip": event.get("src_ip"),
                "dest_ip": event.get("dest_ip"),

                "src_port": event.get("src_port"),
                "dest_port": event.get("dest_port"),

                "timestamp": event.get("ts"),

                "service": event.get("service"),
                "proto": event.get("proto"),
                "conn_state": event.get("conn_state"),

                "tactic": event.get("tactic"),

                "source_release": event.get(
                    "source_release",
                    "unknown"
                ),
            }

            alerts.append(alert)

        except Exception as error:

            print(
                f"[RULE ERROR] "
                f"{rule.__name__}: {error}"
            )

    return alerts