from rules.detections import (
    rule_brute_force,
    rule_port_scan,
    rule_large_outbound_transfer,
    rule_dns_burst,
)


# ============================================================
# REGISTERED DETECTION RULES
# ============================================================

RULES = [
    rule_brute_force,
    rule_port_scan,
    rule_large_outbound_transfer,
    rule_dns_burst,
]


def evaluate_event(event):
    """
    Evaluate one Zeek event against every registered detection.

    Returns:
        list[dict]: alerts generated by the event.
    """

    alerts = []

    for rule in RULES:

        try:
            result = rule(event)

            if not result:
                continue

            alert = {
                **result,

                # ------------------------------------------------
                # Common Zeek event context
                # ------------------------------------------------

                "src_ip": event.get("src_ip"),
                "dest_ip": event.get("dest_ip"),

                "src_port": event.get("src_port"),
                "dest_port": event.get("dest_port"),

                "timestamp": event.get("ts"),

                "service": event.get("service"),
                "proto": event.get("proto"),
                "conn_state": event.get("conn_state"),

                "tactic": event.get("tactic"),

                "source_release": event.get(
                    "source_release",
                    "unknown"
                ),
            }

            alerts.append(alert)

        except Exception as error:

            print(
                f"[RULE ERROR] "
                f"{rule.__name__}: {error}"
            )

    return alerts